name: Lint, build and run tests

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: ['12', '14']
      fail-fast: false
    name: ${{ matrix.os }} | Node ${{ matrix.node-version }} latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Print node and yarn versions
        run: |
          node --version
          yarn --version
      - name: Install dependencies
        run: yarn install --frozen-lockfile --check-files
      - name: Run ESLint
        run: yarn lint
        env:
          CI: true
      - name: Build
        run: yarn build
      - name: Run tests
        run: yarn test
        env:
          CI: true
